SELECT RESULTADO.HTML ,

    (SELECT LAQTPORIG.CDESCTPORIG
           FROM LAQTPORIG
          WHERE LAQTPORIG.NCODITPORIG = :P_NCODITPORIG) CDESCTPORIG,
          (SELECT MAX(LAQTPORIG.CDESCTPORIG)
          FROM LAQRECEP , LAQTPORIG
         WHERE LAQRECEP.CSITURECEP = 'A'
           AND LAQTPORIG.NCODITPORIG = LAQRECEP.NCODITPORIG
           AND ((:P_FIL_NCODITPETAP = -1)
                OR
               (LAQRECEP.NCODITPETAP = :P_FIL_NCODITPETAP))
           AND INSTR(UPPER(LAQRECEP.CLOTERECEP),REPLACE(UPPER(:P_CLOTERECEP), '*',' ')) > 0
           AND ((:P_NCODIMERCA = -1 )
                 OR
                (LAQRECEP.NCODIRECEP IN
                            (SELECT LAQRECMER.NCODIRECEP
                               FROM LAQRECMER
                              WHERE LAQRECMER.NCODIMERCA = :P_NCODIMERCA)))) CDESCTPORIG2,
                              nvl( (SELECT MAX( DDATAATUREG )
                   FROM  (SELECT distinct  (SELECT  DISTINCT TO_CHAR(MAX(SYSATUREG.DDATAATUREG),'DD-MM-YYYY  HH24:MI:SS')DDATAATUREG
                  FROM SYSATUREG, SYSUSUAR ,SYSATURERE
                 WHERE SYSATUREG.NCODIUSUAR = SYSUSUAR.NCODIUSUAR
                   AND SYSATURERE.NCODIATUREG = SYSATUREG.NCODIATUREG
                   AND SYSATURERE.CCAMPATURERE = 'NCODIMERCA'
                   AND SYSATUREG.CCAMPATUREG =   'CAVLOMEPAANA'
                   AND SYSATURERE.CVACAATURERE =FATMERCA.NCODIMERCA
                   AND SYSATUREG.DDATAATUREG  =  (SELECT  MAX( SYSATUREG.DDATAATUREG )
                                                    FROM SYSATUREG, SYSUSUAR ,SYSATURERE
                                                   WHERE SYSATUREG.NCODIUSUAR = SYSUSUAR.NCODIUSUAR
                                                     AND SYSATURERE.NCODIATUREG = SYSATUREG.NCODIATUREG
                                                     AND SYSATURERE.CCAMPATURERE = 'NCODIMERCA'
                                                     AND SYSATUREG.CCAMPATUREG = 'CAVLOMEPAANA'
                                                     AND SYSATURERE.CVACAATURERE = FATMERCA.NCODIMERCA) )DDATAATUREG
                  FROM LAQRECEP, FATMERCA, LAQRECMER
                 WHERE LAQRECEP.CSITURECEP = 'A'
                   AND FATMERCA.NCODIMERCA = LAQRECMER.NCODIMERCA
                   AND LAQRECMER.NCODIRECEP = LAQRECEP.NCODIRECEP
                   AND ((:P_FIL_NCODITPETAP = -1)
                      OR
                     (LAQRECEP.NCODITPETAP = :P_FIL_NCODITPETAP))
                   AND INSTR(UPPER(LAQRECEP.CLOTERECEP),REPLACE(UPPER(:P_CLOTERECEP), '*',' ')) > 0
                   AND ((:P_NCODIMERCA = -1 )
                         OR
                        (LAQRECEP.NCODIRECEP IN
                                    (SELECT LAQRECMER.NCODIRECEP
                                       FROM LAQRECMER
                                      WHERE LAQRECMER.NCODIMERCA = :P_NCODIMERCA))))),'SIN ALTERACIÓN') DATA_PARAMETRO,
                               nvl( (SELECT LISTAGG( CNOMEUSUAR , '; ')
         WITHIN GROUP (ORDER BY CNOMEUSUAR)
                FROM (SELECT distinct  (SELECT  DISTINCT MAX(SYSUSUAR.CNOMEUSUAR)
                  FROM SYSATUREG, SYSUSUAR ,SYSATURERE
                 WHERE SYSATUREG.NCODIUSUAR = SYSUSUAR.NCODIUSUAR
                   AND SYSATURERE.NCODIATUREG = SYSATUREG.NCODIATUREG
                   AND SYSATURERE.CCAMPATURERE = 'NCODIMERCA'
                   AND SYSATUREG.CCAMPATUREG =   'CAVLOMEPAANA'
                   AND SYSATURERE.CVACAATURERE =FATMERCA.NCODIMERCA
                   AND SYSATUREG.DDATAATUREG  =  (SELECT  MAX( SYSATUREG.DDATAATUREG )
                                                    FROM SYSATUREG, SYSUSUAR ,SYSATURERE
                                                   WHERE SYSATUREG.NCODIUSUAR = SYSUSUAR.NCODIUSUAR
                                                     AND SYSATURERE.NCODIATUREG = SYSATUREG.NCODIATUREG
                                                     AND SYSATURERE.CCAMPATURERE = 'NCODIMERCA'
                                                     AND SYSATUREG.CCAMPATUREG = 'CAVLOMEPAANA'
                                                     AND SYSATURERE.CVACAATURERE = FATMERCA.NCODIMERCA) )CNOMEUSUAR
                  FROM LAQRECEP, FATMERCA, LAQRECMER
                 WHERE LAQRECEP.CSITURECEP = 'A'
                   AND FATMERCA.NCODIMERCA = LAQRECMER.NCODIMERCA
                   AND LAQRECMER.NCODIRECEP = LAQRECEP.NCODIRECEP
                   AND ((:P_FIL_NCODITPETAP = -1)
                      OR
                     (LAQRECEP.NCODITPETAP = :P_FIL_NCODITPETAP))
                   AND INSTR(UPPER(LAQRECEP.CLOTERECEP),REPLACE(UPPER(:P_CLOTERECEP), '*',' ')) > 0
                   AND ((:P_NCODIMERCA = -1 )
                         OR
                        (LAQRECEP.NCODIRECEP IN
                                    (SELECT LAQRECMER.NCODIRECEP
                                       FROM LAQRECMER
                                      WHERE LAQRECMER.NCODIMERCA = :P_NCODIMERCA))))),'SIN ALTERACIÓN') USUAR_PARAMETRO,
            (SELECT SYSUSUAR.CNOMEUSUAR
          FROM LAQRECEP, SYSUSUAR
         WHERE LAQRECEP.CSITURECEP = 'A'
           AND LAQRECEP.NCODIUSUAR = SYSUSUAR.NCODIUSUAR
           AND LAQRECEP.NCODIRECEP IN (
                                       (SELECT MAX(LAQRECEP.NCODIRECEP)
                                          FROM LAQRECEP
                                         WHERE LAQRECEP.CSITURECEP = 'A'
                                            AND ((:P_FIL_NCODITPETAP = -1)
                                                    OR
                                                 (LAQRECEP.NCODITPETAP = :P_FIL_NCODITPETAP))
                                           AND INSTR(UPPER(LAQRECEP.CLOTERECEP),REPLACE(UPPER(:P_CLOTERECEP) , '*',' ')) > 0
                                           AND ((:P_NCODIMERCA = -1 )
                                                 OR
                                                (LAQRECEP.NCODIRECEP IN
                                                            (SELECT LAQRECMER.NCODIRECEP
                                                               FROM LAQRECMER
                                                              WHERE LAQRECMER.NCODIMERCA = :P_NCODIMERCA))))))RECIBIDO_POR ,
 
          (SELECT MAX(LAQRECEP.DDATARECEP)
          FROM LAQRECEP
         WHERE LAQRECEP.CSITURECEP = 'A'
           AND ((:P_FIL_NCODITPETAP = -1)
                OR
               (LAQRECEP.NCODITPETAP = :P_FIL_NCODITPETAP))
           AND INSTR(UPPER(LAQRECEP.CLOTERECEP),REPLACE(UPPER(:P_CLOTERECEP), '*',' ')) > 0
           AND ((:P_NCODIMERCA = -1 )
                 OR
                (LAQRECEP.NCODIRECEP IN
                            (SELECT LAQRECMER.NCODIRECEP
                               FROM LAQRECMER
                              WHERE LAQRECMER.NCODIMERCA = :P_NCODIMERCA)))) DDATARECEP,
          (SELECT MAX(LAQANALI.DDATAANALI)
          FROM LAQRECEP, LAQRECANAL, LAQANALI
         WHERE LAQANALI.CSITUANALI = 'A'
           AND LAQANALI.NCODIANALI = LAQRECANAL.NCODIANALI
           AND LAQRECANAL.NCODIRECEP = LAQRECEP.NCODIRECEP
           AND ((:P_FIL_NCODITPETAP = -1)
                OR
               (LAQRECEP.NCODITPETAP = :P_FIL_NCODITPETAP))
           AND INSTR(UPPER(LAQRECEP.CLOTERECEP), REPLACE(UPPER(:P_CLOTERECEP) , '*',' ')) > 0
           AND ((:P_NCODIMERCA = -1 )
                 OR
                (LAQRECEP.NCODIRECEP IN
                            (SELECT LAQRECMER.NCODIRECEP
                               FROM LAQRECMER
                              WHERE LAQRECMER.NCODIMERCA = :P_NCODIMERCA))))DDATAANALI,
                              (SELECT LISTAGG( MERCA  , ' <br> ' )   WITHIN GROUP (ORDER BY MERCA) FROM ( SELECT  DISTINCT   CASE
                     WHEN FATMERCA.NCODIMERCA = -99 THEN
                       LAQRECEP.CPRODRECEP ||' ('||FATMERCA.NCODIMERCA||')'
                     ELSE
                       FATMERCA.CNOMEMERCA||' ('||FATMERCA.NCODIMERCA||')'
                     END MERCA
          FROM LAQRECEP  , FATMERCA, LAQRECMER
         WHERE LAQRECEP.CSITURECEP = 'A'
           AND  FATMERCA.NCODIMERCA = LAQRECMER.NCODIMERCA
            AND LAQRECMER.NCODIRECEP = LAQRECEP.NCODIRECEP
                   AND ((:P_FIL_NCODITPETAP = -1)
                OR
               (LAQRECEP.NCODITPETAP = :P_FIL_NCODITPETAP))
           AND INSTR(UPPER(LAQRECEP.CLOTERECEP),REPLACE(UPPER(:P_CLOTERECEP), '*',' ')) > 0
           AND ((:P_NCODIMERCA = -1 )
                 OR
                (LAQRECEP.NCODIRECEP IN
                            (SELECT LAQRECMER.NCODIRECEP
                               FROM LAQRECMER
                              WHERE LAQRECMER.NCODIMERCA = :P_NCODIMERCA))))) PRODUTO
 FROM (SELECT SEGUIMIENTO_RESULTADOS_PACK.F_RETURN_SEG_RESUL_HTML2(REPLACE( :P_CLOTERECEP , '*',' ') , :P_NCODITPORIG, 1 ,5, :P_TPFORMSEARCH  ,LAQTPETAP.NCODITPETAP, :P_NCODIMERCA) HTML
             FROM DUAL   ,LAQTPETAP
         WHERE LAQTPETAP.CSITUTPETAP = 'A'
           AND ((:P_FIL_NCODITPETAP = -1)
              OR
              (LAQTPETAP.NCODITPETAP = :P_FIL_NCODITPETAP))
         UNION ALL
        SELECT  SEGUIMIENTO_RESULTADOS_PACK.F_RETURN_SEG_RESUL_HTML2(REPLACE( :P_CLOTERECEP , '*',' ') , :P_NCODITPORIG, 6,10, :P_TPFORMSEARCH ,LAQTPETAP.NCODITPETAP, :P_NCODIMERCA)  HTML
             FROM DUAL   ,LAQTPETAP
         WHERE LAQTPETAP.CSITUTPETAP = 'A'
   AND ((:P_FIL_NCODITPETAP = -1)
              OR
              (LAQTPETAP.NCODITPETAP = :P_FIL_NCODITPETAP))
         UNION ALL
        SELECT  SEGUIMIENTO_RESULTADOS_PACK.F_RETURN_SEG_RESUL_HTML2(REPLACE( :P_CLOTERECEP , '*',' ') , :P_NCODITPORIG, 11 ,15, :P_TPFORMSEARCH ,LAQTPETAP.NCODITPETAP, :P_NCODIMERCA) HTML
            FROM DUAL   ,LAQTPETAP
         WHERE LAQTPETAP.CSITUTPETAP = 'A'
   AND ((:P_FIL_NCODITPETAP = -1)
              OR
              (LAQTPETAP.NCODITPETAP = :P_FIL_NCODITPETAP))
         UNION ALL
        SELECT SEGUIMIENTO_RESULTADOS_PACK.F_RETURN_SEG_RESUL_HTML2(REPLACE( :P_CLOTERECEP , '*',' ') , :P_NCODITPORIG, 16 ,20 , :P_TPFORMSEARCH  ,LAQTPETAP.NCODITPETAP, :P_NCODIMERCA) HTML
          FROM DUAL   ,LAQTPETAP
         WHERE LAQTPETAP.CSITUTPETAP = 'A'
   AND ((:P_FIL_NCODITPETAP = -1)
              OR
              (LAQTPETAP.NCODITPETAP = :P_FIL_NCODITPETAP))
         UNION ALL
        SELECT SEGUIMIENTO_RESULTADOS_PACK.F_RETURN_SEG_RESUL_HTML2(REPLACE( :P_CLOTERECEP , '*',' ') , :P_NCODITPORIG, 21,25, :P_TPFORMSEARCH  ,LAQTPETAP.NCODITPETAP, :P_NCODIMERCA) HTML
            FROM DUAL   ,LAQTPETAP
         WHERE LAQTPETAP.CSITUTPETAP = 'A'
   AND ((:P_FIL_NCODITPETAP = -1)
              OR
              (LAQTPETAP.NCODITPETAP = :P_FIL_NCODITPETAP))
         UNION ALL
        SELECT SEGUIMIENTO_RESULTADOS_PACK.F_RETURN_SEG_RESUL_HTML2(REPLACE( :P_CLOTERECEP , '*',' ') , :P_NCODITPORIG, 31 ,35 , :P_TPFORMSEARCH  ,LAQTPETAP.NCODITPETAP, :P_NCODIMERCA)  HTML
           FROM DUAL   ,LAQTPETAP
         WHERE LAQTPETAP.CSITUTPETAP = 'A'
   AND ((:P_FIL_NCODITPETAP = -1)
              OR
              (LAQTPETAP.NCODITPETAP = :P_FIL_NCODITPETAP))

         UNION ALL
        SELECT SEGUIMIENTO_RESULTADOS_PACK.F_RETURN_SEG_RESUL_HTML2(REPLACE( :P_CLOTERECEP , '*',' ') , :P_NCODITPORIG, 36 ,40 , :P_TPFORMSEARCH  ,LAQTPETAP.NCODITPETAP, :P_NCODIMERCA)  HTML
           FROM DUAL   ,LAQTPETAP
         WHERE LAQTPETAP.CSITUTPETAP = 'A'
   AND ((:P_FIL_NCODITPETAP = -1)
              OR
              (LAQTPETAP.NCODITPETAP = :P_FIL_NCODITPETAP))
         UNION ALL
        SELECT SEGUIMIENTO_RESULTADOS_PACK.F_RETURN_SEG_RESUL_HTML2(REPLACE( :P_CLOTERECEP , '*',' ') , :P_NCODITPORIG, 41 ,45 , :P_TPFORMSEARCH  ,LAQTPETAP.NCODITPETAP, :P_NCODIMERCA)  HTML
            FROM DUAL   ,LAQTPETAP
         WHERE LAQTPETAP.CSITUTPETAP = 'A'
   AND ((:P_FIL_NCODITPETAP = -1)
              OR
              (LAQTPETAP.NCODITPETAP = :P_FIL_NCODITPETAP))
         UNION ALL
        SELECT SEGUIMIENTO_RESULTADOS_PACK.F_RETURN_SEG_RESUL_HTML2(REPLACE( :P_CLOTERECEP , '*',' ') , :P_NCODITPORIG, 46 ,50 , :P_TPFORMSEARCH  ,LAQTPETAP.NCODITPETAP, :P_NCODIMERCA)  HTML
          FROM DUAL   ,LAQTPETAP
         WHERE LAQTPETAP.CSITUTPETAP = 'A'
   AND ((:P_FIL_NCODITPETAP = -1)
              OR
              (LAQTPETAP.NCODITPETAP = :P_FIL_NCODITPETAP))
         UNION ALL
        SELECT SEGUIMIENTO_RESULTADOS_PACK.F_RETURN_SEG_RESUL_HTML2(REPLACE( :P_CLOTERECEP , '*',' ') , :P_NCODITPORIG, 51 ,55 , :P_TPFORMSEARCH  ,LAQTPETAP.NCODITPETAP, :P_NCODIMERCA)  HTML
            FROM DUAL   ,LAQTPETAP
         WHERE LAQTPETAP.CSITUTPETAP = 'A'
   AND ((:P_FIL_NCODITPETAP = -1)
              OR
              (LAQTPETAP.NCODITPETAP = :P_FIL_NCODITPETAP))
         UNION ALL
        SELECT SEGUIMIENTO_RESULTADOS_PACK.F_RETURN_SEG_RESUL_HTML2(REPLACE( :P_CLOTERECEP , '*',' ') , :P_NCODITPORIG, 56 ,60 , :P_TPFORMSEARCH  ,LAQTPETAP.NCODITPETAP, :P_NCODIMERCA)  HTML
          FROM DUAL   ,LAQTPETAP
         WHERE LAQTPETAP.CSITUTPETAP = 'A'
   AND ((:P_FIL_NCODITPETAP = -1)
              OR
              (LAQTPETAP.NCODITPETAP = :P_FIL_NCODITPETAP))
         UNION ALL
        SELECT SEGUIMIENTO_RESULTADOS_PACK.F_RETURN_SEG_RESUL_HTML2(REPLACE( :P_CLOTERECEP , '*',' ') , :P_NCODITPORIG, 61 ,65 , :P_TPFORMSEARCH  ,LAQTPETAP.NCODITPETAP, :P_NCODIMERCA)  HTML
         FROM DUAL   ,LAQTPETAP
         WHERE LAQTPETAP.CSITUTPETAP = 'A'
   AND ((:P_FIL_NCODITPETAP = -1)
              OR
              (LAQTPETAP.NCODITPETAP = :P_FIL_NCODITPETAP))
         UNION ALL
        SELECT SEGUIMIENTO_RESULTADOS_PACK.F_RETURN_SEG_RESUL_HTML2(REPLACE( :P_CLOTERECEP , '*',' ') , :P_NCODITPORIG, 66 ,70 , :P_TPFORMSEARCH  ,LAQTPETAP.NCODITPETAP, :P_NCODIMERCA)  HTML
         FROM DUAL   ,LAQTPETAP
         WHERE LAQTPETAP.CSITUTPETAP = 'A'
   AND ((:P_FIL_NCODITPETAP = -1)
              OR
              (LAQTPETAP.NCODITPETAP = :P_FIL_NCODITPETAP))
          )RESULTADO
  WHERE HTML IS NOT NULL