SELECT RESULTADO.HTML ,

    (SELECT LAQTPORIG.CDESCTPORIG
           FROM LAQTPORIG
          WHERE LAQTPORIG.NCODITPORIG = :P_NCODITPORIG) CDESCTPORIG 
 FROM (SELECT SEGUIMIENTO_RESULTADOS_PACK.F_RETURN_SEG_RESUL_HTML2(REPLACE( :P_CLOTERECEP , '*',' ') , :P_NCODITPORIG, 1 ,5, :P_TPFORMSEARCH  ,LAQTPETAP.NCODITPETAP, :P_NCODIMERCA) HTML
             FROM DUAL   ,LAQTPETAP
         WHERE LAQTPETAP.CSITUTPETAP = 'A'
           AND ((:P_FIL_NCODITPETAP = -1)
              OR
              (LAQTPETAP.NCODITPETAP = :P_FIL_NCODITPETAP))
         UNION ALL
        SELECT  SEGUIMIENTO_RESULTADOS_PACK.F_RETURN_SEG_RESUL_HTML2(REPLACE( :P_CLOTERECEP , '*',' ') , :P_NCODITPORIG, 6,10, :P_TPFORMSEARCH ,LAQTPETAP.NCODITPETAP, :P_NCODIMERCA)  HTML
             FROM DUAL   ,LAQTPETAP
         WHERE LAQTPETAP.CSITUTPETAP = 'A'
   AND ((:P_FIL_NCODITPETAP = -1)
              OR
              (LAQTPETAP.NCODITPETAP = :P_FIL_NCODITPETAP))
         UNION ALL
        SELECT  SEGUIMIENTO_RESULTADOS_PACK.F_RETURN_SEG_RESUL_HTML2(REPLACE( :P_CLOTERECEP , '*',' ') , :P_NCODITPORIG, 11 ,15, :P_TPFORMSEARCH ,LAQTPETAP.NCODITPETAP, :P_NCODIMERCA) HTML
            FROM DUAL   ,LAQTPETAP
         WHERE LAQTPETAP.CSITUTPETAP = 'A'
   AND ((:P_FIL_NCODITPETAP = -1)
              OR
              (LAQTPETAP.NCODITPETAP = :P_FIL_NCODITPETAP))
         UNION ALL
        SELECT SEGUIMIENTO_RESULTADOS_PACK.F_RETURN_SEG_RESUL_HTML2(REPLACE( :P_CLOTERECEP , '*',' ') , :P_NCODITPORIG, 16 ,20 , :P_TPFORMSEARCH  ,LAQTPETAP.NCODITPETAP, :P_NCODIMERCA) HTML
          FROM DUAL   ,LAQTPETAP
         WHERE LAQTPETAP.CSITUTPETAP = 'A'
   AND ((:P_FIL_NCODITPETAP = -1)
              OR
              (LAQTPETAP.NCODITPETAP = :P_FIL_NCODITPETAP))
         UNION ALL
        SELECT SEGUIMIENTO_RESULTADOS_PACK.F_RETURN_SEG_RESUL_HTML2(REPLACE( :P_CLOTERECEP , '*',' ') , :P_NCODITPORIG, 21,25, :P_TPFORMSEARCH  ,LAQTPETAP.NCODITPETAP, :P_NCODIMERCA) HTML
            FROM DUAL   ,LAQTPETAP
         WHERE LAQTPETAP.CSITUTPETAP = 'A'
   AND ((:P_FIL_NCODITPETAP = -1)
              OR
              (LAQTPETAP.NCODITPETAP = :P_FIL_NCODITPETAP))
         UNION ALL
        SELECT SEGUIMIENTO_RESULTADOS_PACK.F_RETURN_SEG_RESUL_HTML2(REPLACE( :P_CLOTERECEP , '*',' ') , :P_NCODITPORIG, 31 ,35 , :P_TPFORMSEARCH  ,LAQTPETAP.NCODITPETAP, :P_NCODIMERCA)  HTML
           FROM DUAL   ,LAQTPETAP
         WHERE LAQTPETAP.CSITUTPETAP = 'A'
   AND ((:P_FIL_NCODITPETAP = -1)
              OR
              (LAQTPETAP.NCODITPETAP = :P_FIL_NCODITPETAP))

         UNION ALL
        SELECT SEGUIMIENTO_RESULTADOS_PACK.F_RETURN_SEG_RESUL_HTML2(REPLACE( :P_CLOTERECEP , '*',' ') , :P_NCODITPORIG, 36 ,40 , :P_TPFORMSEARCH  ,LAQTPETAP.NCODITPETAP, :P_NCODIMERCA)  HTML
           FROM DUAL   ,LAQTPETAP
         WHERE LAQTPETAP.CSITUTPETAP = 'A'
   AND ((:P_FIL_NCODITPETAP = -1)
              OR
              (LAQTPETAP.NCODITPETAP = :P_FIL_NCODITPETAP))
         UNION ALL
        SELECT SEGUIMIENTO_RESULTADOS_PACK.F_RETURN_SEG_RESUL_HTML2(REPLACE( :P_CLOTERECEP , '*',' ') , :P_NCODITPORIG, 41 ,45 , :P_TPFORMSEARCH  ,LAQTPETAP.NCODITPETAP, :P_NCODIMERCA)  HTML
            FROM DUAL   ,LAQTPETAP
         WHERE LAQTPETAP.CSITUTPETAP = 'A'
   AND ((:P_FIL_NCODITPETAP = -1)
              OR
              (LAQTPETAP.NCODITPETAP = :P_FIL_NCODITPETAP))
         UNION ALL
        SELECT SEGUIMIENTO_RESULTADOS_PACK.F_RETURN_SEG_RESUL_HTML2(REPLACE( :P_CLOTERECEP , '*',' ') , :P_NCODITPORIG, 46 ,50 , :P_TPFORMSEARCH  ,LAQTPETAP.NCODITPETAP, :P_NCODIMERCA)  HTML
          FROM DUAL   ,LAQTPETAP
         WHERE LAQTPETAP.CSITUTPETAP = 'A'
   AND ((:P_FIL_NCODITPETAP = -1)
              OR
              (LAQTPETAP.NCODITPETAP = :P_FIL_NCODITPETAP))
         UNION ALL
        SELECT SEGUIMIENTO_RESULTADOS_PACK.F_RETURN_SEG_RESUL_HTML2(REPLACE( :P_CLOTERECEP , '*',' ') , :P_NCODITPORIG, 51 ,55 , :P_TPFORMSEARCH  ,LAQTPETAP.NCODITPETAP, :P_NCODIMERCA)  HTML
            FROM DUAL   ,LAQTPETAP
         WHERE LAQTPETAP.CSITUTPETAP = 'A'
   AND ((:P_FIL_NCODITPETAP = -1)
              OR
              (LAQTPETAP.NCODITPETAP = :P_FIL_NCODITPETAP))
         UNION ALL
        SELECT SEGUIMIENTO_RESULTADOS_PACK.F_RETURN_SEG_RESUL_HTML2(REPLACE( :P_CLOTERECEP , '*',' ') , :P_NCODITPORIG, 56 ,60 , :P_TPFORMSEARCH  ,LAQTPETAP.NCODITPETAP, :P_NCODIMERCA)  HTML
          FROM DUAL   ,LAQTPETAP
         WHERE LAQTPETAP.CSITUTPETAP = 'A'
   AND ((:P_FIL_NCODITPETAP = -1)
              OR
              (LAQTPETAP.NCODITPETAP = :P_FIL_NCODITPETAP))
         UNION ALL
        SELECT SEGUIMIENTO_RESULTADOS_PACK.F_RETURN_SEG_RESUL_HTML2(REPLACE( :P_CLOTERECEP , '*',' ') , :P_NCODITPORIG, 61 ,65 , :P_TPFORMSEARCH  ,LAQTPETAP.NCODITPETAP, :P_NCODIMERCA)  HTML
         FROM DUAL   ,LAQTPETAP
         WHERE LAQTPETAP.CSITUTPETAP = 'A'
   AND ((:P_FIL_NCODITPETAP = -1)
              OR
              (LAQTPETAP.NCODITPETAP = :P_FIL_NCODITPETAP))
         UNION ALL
        SELECT SEGUIMIENTO_RESULTADOS_PACK.F_RETURN_SEG_RESUL_HTML2(REPLACE( :P_CLOTERECEP , '*',' ') , :P_NCODITPORIG, 66 ,70 , :P_TPFORMSEARCH  ,LAQTPETAP.NCODITPETAP, :P_NCODIMERCA)  HTML
         FROM DUAL   ,LAQTPETAP
         WHERE LAQTPETAP.CSITUTPETAP = 'A'
   AND ((:P_FIL_NCODITPETAP = -1)
              OR
              (LAQTPETAP.NCODITPETAP = :P_FIL_NCODITPETAP))
          )RESULTADO
  WHERE HTML IS NOT NULL